#-------------------------------------------------
# This file is generated by the Qt Creator
#-------------------------------------------------

THIS_DIR = $$PWD/../../..

QT += gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

DEFINES += \
    PRO_COMPONENT

include($$THIS_DIR/source/common/build.pri)

TARGET = $$qtLibraryTarget(com_demo2)

# The .h file which was generated for your project. Feel free to hack it.
HEADERS += \
    $$PWD/com_demo2.h \
    $$PWD/testwidget1.h

# The .cpp file which was generated for your project. Feel free to hack it.
SOURCES += \
    $$PWD/com_demo2.cpp \
    $$PWD/testwidget1.cpp

#
exists($$PWD/com_demo2.xml) {
    OTHER_FILES += \
        $$PWD/com_demo2.xml
}

#-------------------------------------------------
# import libraries
#-------------------------------------------------

#-------------------------------------------------
# global commands
#-------------------------------------------------

win32|unix: {
    commands += echo --- console - $$TARGET --- &

    ## copy files
    dstdir = $$THIS_DIR/component/com_demo2
    win32:dstdir = $$replace(dstdir, /, \\)
    !exists("$$dstdir"):commands += $(MKDIR) "\"$$dstdir\"" &
    srcfile = $$PWD/com_demo2.xml
    win32:srcfile = $$replace(srcfile, /, \\)
    exists("$$srcfile"):commands += $(COPY_FILE) "\"$$srcfile\"" "\"$$dstdir\"" &

    QMAKE_POST_LINK += $$commands
}
