#-------------------------------------------------
# This file is generated by the Qt Creator
#-------------------------------------------------

THIS_DIR = $$PWD/../../../..

@if '%{IncludeIJComponentUi}'
QT += gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
@endif

DEFINES += \\
    PRO_COMPONENT

include($$THIS_DIR/source/common/build.pri)

TARGET = $$qtLibraryTarget(%{ProjectName})

# The .h file which was generated for your project. Feel free to hack it.
HEADERS += \\
    $$PWD/%{HdrFileName} \\
@if '%{IncludeIJComponentUi}'
    $$PWD/%{UiHdrFileName}
@endif

# The .cpp file which was generated for your project. Feel free to hack it.
SOURCES += \\
    $$PWD/%{SrcFileName} \\
@if '%{IncludeIJComponentUi}'
    $$PWD/%{UiSrcFileName}
@endif

@if '%{IncludeConfigFile}'
#
exists($$PWD/%{ProjectName}.xml) {
    OTHER_FILES += \\
        $$PWD/%{ProjectName}.xml
}

@endif
#-------------------------------------------------
# import libraries
#-------------------------------------------------

#-------------------------------------------------
# global commands
#-------------------------------------------------

win32|unix: {
    commands += echo --- console - %{ProjectName} --- &

    ## copy files
    dstdir = $$THIS_DIR/component/$$(JFRAME_APPNAME)/%{ProjectName}/
    win32:dstdir = $$replace(dstdir, /, \\\\)
    !exists("$$dstdir"):commands += $(MKDIR) "\\"$$dstdir\\"" &
@if '%{IncludeConfigFile}'
    srcfile = $$PWD/%{ProjectName}.xml
    win32:srcfile = $$replace(srcfile, /, \\\\)
    exists("$$srcfile"):commands += $(COPY_FILE) "\\"$$srcfile\\"" "\\"$$dstdir\\"" &
@endif

    QMAKE_POST_LINK += $$commands
}
