#-------------------------------------------------
# This file is generated by the Qt Creator
#-------------------------------------------------

THIS_DIR = $$PWD/../../..

QT += gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

DEFINES += \
    PRO_COMPONENT \
    QWT_LIB \
    JCUSTOMPLOT_LIB

include($$THIS_DIR/source/common/build.pri)

TARGET = $$qtLibraryTarget(customplot_test)

# The .h file which was generated for your project. Feel free to hack it.
HEADERS += \
    $$PWD/customplottest.h \
    $$PWD/customplottestui.h

# The .cpp file which was generated for your project. Feel free to hack it.
SOURCES += \
    $$PWD/customplottest.cpp \
    $$PWD/customplottestui.cpp

#
exists($$PWD/customplot_test.xml) {
    OTHER_FILES += \
        $$PWD/customplot_test.xml
}

#-------------------------------------------------
# import libraries
#-------------------------------------------------

#-------------------------------------------------
# global commands
#-------------------------------------------------

win32|unix: {
    commands += echo --- console - customplot_test --- &

    ## copy files
    dstdir = $$THIS_DIR/component/customplot_test/
    win32:dstdir = $$replace(dstdir, /, \\)
    !exists("$$dstdir"):commands += $(MKDIR) "\"$$dstdir\"" &
    srcfile = $$PWD/customplot_test.xml
    win32:srcfile = $$replace(srcfile, /, \\)
    exists("$$srcfile"):commands += $(COPY_FILE) "\"$$srcfile\"" "\"$$dstdir\"" &

    QMAKE_POST_LINK += $$commands
}
