#-------------------------------------------------
# This file is generated by the Qt Creator
#-------------------------------------------------

jframe_root = $$PWD/../../../..

QT += gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

DEFINES += \
    PRO_COMPONENT \
    JFRAME_COMPONENT

include($${jframe_root}/source/common/build.pri)

TARGET = $$qtLibraryTarget(jcom_login)

# The .h file which was generated for your project. Feel free to hack it.
HEADERS += \
    $$PWD/jcom_login.h

# The .cpp file which was generated for your project. Feel free to hack it.
SOURCES += \
    $$PWD/jcom_login.cpp

#
exists($$PWD/jcom_login.xml) {
    OTHER_FILES += \
        $$PWD/jcom_login.xml
}

#-------------------------------------------------
# import libraries
#-------------------------------------------------

#-------------------------------------------------
# global commands
#-------------------------------------------------

win32|unix: {
    copyCommand = @echo off
    copyCommand += && @echo ---- console - jcom_login ----

    ## copy files
    dstdir = $${jframe_root}/component/jframe/jcom_login
    win32:dstdir = $$replace(dstdir, /, \\)
    !exists("$$dstdir"):copyCommand += && $(MKDIR) "$$dstdir"
    srcfile = $$PWD/jcom_login.xml
    win32:srcfile = $$replace(srcfile, /, \\)
    exists("$$srcfile"):copyCommand += && $(COPY_FILE) "$$srcfile" "$$dstdir"

    deployment.commands = $$copyCommand
    first.depends = $(first) deployment
    QMAKE_EXTRA_TARGETS += first deployment
}
