#-------------------------------------------------
# This file is generated by the Qt Creator
#-------------------------------------------------

THIS_DIR = $$PWD/../../../..

QT += gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

DEFINES += \
    PRO_COMPONENT \
    JFRAME_COMPONENT

include($$THIS_DIR/source/common/build.pri)

TARGET = $$qtLibraryTarget(jcom_login)

# The .h file which was generated for your project. Feel free to hack it.
HEADERS += \
    $$PWD/jcom_login.h

# The .cpp file which was generated for your project. Feel free to hack it.
SOURCES += \
    $$PWD/jcom_login.cpp

#
exists($$PWD/jcom_login.xml) {
    OTHER_FILES += \
        $$PWD/jcom_login.xml
}

#-------------------------------------------------
# import libraries
#-------------------------------------------------

#-------------------------------------------------
# global commands
#-------------------------------------------------

win32|unix: {
    commands += echo --- console - $$TARGET --- &

    ## copy files
    dstdir = $$THIS_DIR/component/jframe/jcom_login
    win32:dstdir = $$replace(dstdir, /, \\)
    !exists("$$dstdir"):commands += $(MKDIR) "\"$$dstdir\"" &
    srcfile = $$PWD/jcom_login.xml
    win32:srcfile = $$replace(srcfile, /, \\)
    exists("$$srcfile"):commands += $(COPY_FILE) "\"$$srcfile\"" "\"$$dstdir\"" &

    QMAKE_POST_LINK += $$commands
}
