#-------------------------------------------------
# This file is generated by the Qt Creator
#-------------------------------------------------

jframe_root = $$PWD/../../../..

QT += gui xml

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

DEFINES += \
    PRO_COMPONENT \
    JFRAME_COMPONENT \
    QTRIBBON_LIB

include($${jframe_root}/source/common/build.pri)

TARGET = $$qtLibraryTarget(jcom_layout)

# The .h file which was generated for your project. Feel free to hack it.
HEADERS += \
    $$PWD/jcom_layout.h \
    $$PWD/private/frame_filter.h

# The .cpp file which was generated for your project. Feel free to hack it.
SOURCES += \
    $$PWD/jcom_layout.cpp \
    $$PWD/private/frame_filter.cpp

#
exists($$PWD/jcom_layout.xml) {
    OTHER_FILES += \
        $$PWD/jcom_layout.xml
}

#-------------------------------------------------
# import libraries
#-------------------------------------------------

#-------------------------------------------------
# global commands
#-------------------------------------------------

win32|unix: {
    commands += echo --- console - $$TARGET --- &

    ## copy files
    dstdir = $${jframe_root}/component/jframe/jcom_layout
    win32:dstdir = $$replace(dstdir, /, \\)
    !exists("$$dstdir"):commands += $(MKDIR) "\"$$dstdir\"" &
    srcfile = $$PWD/jcom_layout.xml
    win32:srcfile = $$replace(srcfile, /, \\)
    exists("$$srcfile"):commands += $(COPY_FILE) "\"$$srcfile\"" "\"$$dstdir\"" &

    QMAKE_POST_LINK += $$commands
}
