#-------------------------------------------------
# This file is generated by the Qt Creator
#-------------------------------------------------

jframe_root = $$PWD/../../../..

QT += gui

DEFINES += \
    PRO_COMPONENT \
    JFRAME_COMPONENT

include($${jframe_root}/source/common/build.pri)

TARGET = jcom_frame

# The .h file which was generated for your project. Feel free to hack it.
HEADERS += \
    $$PWD/jcom_frame.h

# The .cpp file which was generated for your project. Feel free to hack it.
SOURCES += \
    $$PWD/jcom_frame.cpp

#
OTHER_FILES += \
    $$PWD/jcom_frame.xml

#-------------------------------------------------
# import libraries
#-------------------------------------------------

#-------------------------------------------------
# global commands
#-------------------------------------------------

win32|unix: {
    copyCommand = @echo off
    copyCommand += && @echo ---- console - $$TARGET ----

    ## copy files
    dstdir = $$(jframe_root)/Component/jframe/$$TARGET
    win32:dstdir = $$replace(dstdir, /, \\)
    !exists("$${dstdir}"):copyCommand += $$ &(MKDIR) "$${dstdir}"
    srcfile = $$PWD/$${TARGET}.xml
    win32:srcfile = $$replace(srcfile, /, \\)
    exists("$${srcfile}"):copyCommand += $$ &(COPY_FILE) "$${srcfile}" "$${dstdir}"

    deployment.commands = $$copyCommand
    first.depends = $(first) deployment
    QMAKE_EXTRA_TARGETS += first deployment
}
